server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/notification_db
    password: admin1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.ecommerce.notification.service.event.OrderCreatedEvent

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
